# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 324e4e0025d099a2dcdee2f50481271eff733c1593bbaae100ec041e50d21878e3f5690eb28e977d30ae38482cb59616f9077f6825a4d0a652b206987fac8e7a

test:
  secret_key_base: d0866ad2496ff931eb096217bfb0fcd508c07003257a473c1ce746beb1065a94f1c560f73c7e2c613a73f7b7673d606021c46b11a012dadb33d4316d54360d5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
